version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/cariad/gorando

    steps:
      - checkout

      - run: mkdir -p /tmp/test-results

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: go get github.com/jstemmer/go-junit-report

      - run:
          name: Run unit tests
          command: go test -v 2>&1 | go-junit-report > /tmp/test-results/report.xml

      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
