version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/cariad/gorando

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run:
          name: Run unit tests
          command: go test -cover > /tmp/test-results.out

      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg

      - store_artifacts:
          path: /tmp/test-results.out
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results.out
